### ISSUE TITLE
Pill component is not being exported

### ISSUE THREAD

**Issue by tjallingt** [tableau/tableau-ui#11]
It is not included in the bundle that is on npm currently, see: https://unpkg.com/@tableau/tableau-ui@2.0.0/lib/src/components/

You can confirm it is actually not in the bundle by going here: https://unpkg.com/@tableau/tableau-ui@2.0.0/dist/tableau-ui.min.js and <kbd>ctrl</kbd> + <kbd>f</kbd> to search for "Pill".

**Comment by craigkovatch** [comment]
Thank you for reporting this rather embarrassing omission. We’ll have a new version out before the end of the week.
