### ISSUE TITLE
Use React.forwardRef on functional components

### ISSUE THREAD

**Issue by tjallingt** [tableau/tableau-ui#12]
https://reactjs.org/docs/forwarding-refs.html

React.forwardRef can be applied to "simple" styled components to give developers access to the underlying dom node. Probably useful on `Button`, `Checkbox`, `DropdownSelect`, `Pill`, `Radio` and `TextField` components.

**Comment by tjallingt** [comment]
ah I'm sorry, admittedly i didn't test them all. I just tried to focus the TextField and it didn't work see this example: https://codesandbox.io/s/m74o6yykv9

**Comment by craigkovatch** [comment]
@tjallingt Version 2.1.0 has been published, could you please verify that refs work as you expect and let me know?
