### ISSUE TITLE
[Suggestion] Add Slider, Toggle and Section components

### ISSUE THREAD

**Issue by tjallingt** [tableau/tableau-ui#13]
[Slider and Toggle are mentioned in the extension-api UX Guidelines](https://tableau.github.io/extensions-api/docs/Interaction_Guidelines/ux_controls_ui_patterns.html#selectors) these look great and it would be amazing if we could just use them like any of the other components. Sliders might be tricky but the toggle should be relatively simple to implement...
![](https://tableau.github.io/extensions-api/docs/Interaction_Guidelines/imgs/3-selectors-cover.png)

What I mean by Section is a little bit more tricky to explain; [in the extension-api UX Guidelines it also mentions how to structure a dialog](https://tableau.github.io/extensions-api/docs/Interaction_Guidelines/ux_controls_ui_patterns.html#dialogs), having a component to easily build out form sections with a nice header and correct padding and margins would be great. Perhaps this component could also make it easy to line up multiple columns of inputs as shown in some of the images.
![](https://tableau.github.io/extensions-api/docs/Interaction_Guidelines/imgs/3-dialogs-standard_specs.png)
![](https://tableau.github.io/extensions-api/docs/Interaction_Guidelines/imgs/3-dialogs-side_tabs_specs.png)
![](https://tableau.github.io/extensions-api/docs/Interaction_Guidelines/imgs/3-dialogs-top_tabs_specs.png)

**Comment by craigkovatch** [comment]
We're already working on `Stepper` :) Will discuss the rest of this with the team.

**Comment by tjallingt** [comment]
Fantastic! Can't wait to be able to use them 😄

**Comment by craigkovatch** [comment]
We're hoping to finish up `Stepper` before the holidays and will look at `Slider` after that.

WRT `Section`, we're actually re-evaluating the screenshots you posted as we may have unintentionally published non-finalized design guidelines.

My own thinking has always been: setting `font-size` and `margin-bottom` on an element is simple enough that creating an API for something like a `Section` (that we then have to support and be careful not to break) is more pain than it's worth. Likewise for something like column alignment -- I think `display: table` or `display: flex` are better options.

But do let me know if you think there's additional value that I'm not considering -- your feedback so far has been super valuable and we really appreciate it.

**Comment by tjallingt** [comment]
Yea the Section component idea is a bit more out there. My basis for wanting just being able to quickly throw together forms that follow your style guide. As you say it would basically only set some margins so I agree it might not really be worth adding.

On another note the DropdownSelects in the style guide show labels but the ones currently in tableau ui don't have the ability to add a label that looks like the label on the TextField.

**Comment by craigkovatch** [comment]
Closing in favor of separate issues ^
