### ISSUE TITLE
Add `Stepper` component

### ISSUE THREAD

**Issue by craigkovatch** [tableau/tableau-ui#15]
Requested by @tjallingt in #13

**Comment by tjallingt** [comment]
Yea I can't really come up with a good use case for a horizontal or left/right Stepper.
And if someone needs it, it should be pretty simple to add two buttons with two svg icons or whatever.

Having a neatly styled cross browser version of
```html
<input type="number"  min="10" max="100" step="5" value="50" />
```
is the most generally useful case.

Kind of crazy idea: Maybe if the Toggle is somehow generic enough it could be part of that? As long as it doesn't interfere with the primary use case it might work.
Having the Toggle be able to contain icons would be great anyway and maybe there is some pattern that would allow a user to simply listen to left/right Toggle but never set a selected side.
I find it hard to say whether this would make the component too generic so maybe this is not that great 😕

I know Kent C Dodds has spend a lot of time making very generic Toggle components to teach React component patterns (I think they quickly become too generic though).

**Comment by craigkovatch** [comment]
I think stepper buttons are "momentary press button" and thus a different UI concept from "toggle button". Almost done with the "neatly styled cross browser version of <input>" though :)

**Comment by tjallingt** [comment]
Yea an end user shouldn't have to write `<Toggle />` where they meant `<Stepper horizontal/>`...
I just meant it as a way to make more sense of having a UI component that is simply two buttons by uniting the implementation of the horizontal Stepper with the Toggle.

Great to hear my number inputs are gonna look amazing soon ✨

**Comment by craigkovatch** [comment]
Fixed in https://www.npmjs.com/package/@tableau/tableau-ui/v/2.2.0
