### ISSUE TITLE
TextField with numeric value 0 displays 0 above the input

### ISSUE THREAD

**Issue by tjallingt** [tableau/tableau-ui#20]
Example code:
```js
<TextField value={0} />
```
Will display like this:
![image](https://user-images.githubusercontent.com/5736783/51618037-c32ce700-1f2d-11e9-8003-9fe849bd03fa.png)

This happens because of the use of the boolean and operator (`&&`) which is used to determine whether to display the TextFieldClearButton. This operator will always return either side of the evaluation which in most cases won't matter since React will not render `false`, `undefined`, `null` or `""` but unfortunately it will show `0`.

This can be replaced by either `Boolean(value) && <TextFieldClearButton />` or `value ? <TextFieldClearButton /> : null`

**Comment by craigkovatch** [comment]
Fixed in https://www.npmjs.com/package/@tableau/tableau-ui/v/2.2.0
