### ISSUE TITLE
TS Property '...' does not exist on type

### ISSUE THREAD

**Issue by tjallingt** [tableau/tableau-ui#21]
Somehow the typings for this library seem to have broken for various elements (I have only checked the TextField, Button and DropDownselect). "Native" props are seemingly not recognized and cause typescript errors. Unsure when this was introduced.

## Example

```js
<TextField value="test" onChange={e => console.log(e.target.value)} />
```

```
Type '{ value: string; onChange: (e: any) => void; }' is not assignable to type 'IntrinsicAttributes & TextFieldProps & RefAttributes<HTMLInputElement>'.
  Property 'onChange' does not exist on type 'IntrinsicAttributes & TextFieldProps & RefAttributes<HTMLInputElement>'.ts(2322)
```

## Live examples
https://codesandbox.io/s/1r4x82678q

**Comment by tjallingt** [comment]
I first encountered this error in create-react-app project so i'm relatively confident that codesandbox isn't causing the issue.

Ill get back to you with the typescript and react versions, cant access them directly right now...
  
i think you can also reproduce using `yarn create react-app --typescript` and adding tableau-ui and inserting some code from the examples (haven't tested it though so maybe it works and its something else)

**Comment by tjallingt** [comment]
Just verified that a fresh install of create-react-app also has these typescript errors:

```sh
yarn create react-app test --typescript
cd test
yarn add @tableau/tableau-ui
```

edit `App.tsx` to be:
```js
import React from 'react';
import { TextField } from '@tableau/tableau-ui';

function App() {
  return <TextField onChange={e => e.target.value} />
}

export default App;
```

Running `yarn start` I get:
```sh
Failed to compile.

D:/dev/test/src/App.tsx
TypeScript error: Type '{ onChange: (e: any) => any; }' is not assignable to type 'IntrinsicAttributes & TextFieldProps & RefAttributes<HTMLInputElement>'.
  Property 'onChange' does not exist on type 'IntrinsicAttributes & TextFieldProps & RefAttributes<HTMLInputElement>'.  TS2322

    3 |
    4 | function App() {
  > 5 |   return <TextField onChange={e => e.target.value} />
      |           ^
    6 | }
    7 |
    8 | export default App;
```

Relevant dependencies:
```
"@tableau/tableau-ui": "^2.2.0",
"@types/react": "16.8.13",
"@types/react-dom": "16.8.3",
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-scripts": "2.1.8",
"typescript": "3.4.2"
```

**Comment by tjallingt** [comment]
Digging around on https://unpkg.com/@tableau/tableau-ui@2.2.0/ i believe this line is the cause:
```js
import { OmitRef } from './TypeUtil';
```
It seems that file isn't being shipped and somehow the types passed through it seem to disappear (I guess they turn into `any` or `unknown` or something).

I think you can also use `React.PropsWithoutRef` to achieve the same behaviour...

**Comment by tjallingt** [comment]
@craigkovatch could you take a look at the missing `TypeUtil` file?

**Comment by craigkovatch** [comment]
Is this an immediately-blocking issue for you? Spinning a lot of plates over here :) I probably won't be able to dig in until at least next week.

**Comment by tjallingt** [comment]
I understand, its not really a priority for me (although id love to see it fixed)

**Comment by devbhosale** [comment]
@craigkovatch I am stuck at similar error as well trying to compile on Tableau extension that uses tab-UI

**Comment by craigkovatch** [comment]
Current plan is to get this fixed this week.

**Comment by craigkovatch** [comment]
Sorry for the wait on this. This is still on our radar and on the June schedule. The next release is likely to require TypeScript 3.5 in order to clean this up a little bit, as `Omit<>` is supported natively in 3.5.

**Comment by tjallingt** [comment]
Does the `React.PropsWithoutRef` generic not do the trick? It seemed to work when I tested it on my end (but I didn't look to much into it).

**Comment by dguelfi** [comment]
@craigkovatch I also ran into this issue (incorporating Buttons and TextFields) and would appreciate a fix for this, please.

**Comment by craigkovatch** [comment]
Think I've got this fixed; should release later this week. Our apologies again for the delay, we love that you use this library and we generally try to get things done much quicker but have had many important demands to balance in the past few months. Hold on just a little bit longer :)

**Comment by craigkovatch** [comment]
Version 2.2.1 has been shipped, please verify and close this issue if it's fixed :)

**Comment by dguelfi** [comment]
Have tested the new version 2.2.1 and can confirm that it has fixed my issue. Thanks for your help, @craigkovatch !

**Comment by tjallingt** [comment]
Great! thank you so much @craigkovatch 🙌
