### ISSUE TITLE
Add `Textarea` component

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/tableau-ui#22]
Would be great to have a textarea component. We have users which are adding descriptions and the current <Textfield /> is too small for this.

**Comment by zachledoux** [comment]
Thanks for getting in touch and suggesting this.  We've recently developed this component and will be pushing it to Tableau UI in the near future.  Will message you when it's available.

**Comment by craigkovatch** [comment]
Hi, just wanted to confirm we haven't forgotten about this. We are putting the finishing touches on the 3.0 release and expect to have it out before the end of 2019.

**Comment by merlijnbuit** [comment]
Thank you, looking forward to the release!

**Comment by craigkovatch** [comment]
Version 3.0.0 has been published and includes a new `TextArea` component.
