### ISSUE TITLE
Access for People Operations Project 

### ISSUE THREAD

**Issue by cagerter** [tableau/tableau-ui#24]
Courtney Agerter requests read permission for the People Operations Project in the HR server.

**Comment by craigkovatch** [comment]
@cagerter what is this issue about? Not sure what you are requesting here.

**Comment by cagerter** [comment]
Hi Craig,

I am looking to get access to the People Operations Project tableau. I was told by Lesley Clayton to submit a server issue request to the Tableau Admin team. However, I am not sure I requested that correctly.

I am referencing this specific tableau https://tableau-hr.thefacebook.com/#/explore.

Please let me know if that helps or if I have made the request in the wrong place.

Thanks!
Courtney

**Comment by craigkovatch** [comment]
@cagerter I am not exactly sure what that is, but this is definitely not the page for it. It sounds like you are looking for access to a particular Tableau instance within your organization. This page is only about the UI library that Tableau publishes. I would suggest asking Lesley for further instruction; closing this issue as we won't be able to help you here.

**Comment by cagerter** [comment]
Hi Craig,

Thanks for following up and apologies for extra churn.

I will go back to Lesley.

Thanks!
Courtney
