### ISSUE TITLE
DropdownSelect removes spaces from items

### ISSUE THREAD

**Issue by tagyoureit** [tableau/tableau-ui#27]
I'm passing some values to this component that have multiple spaces in the names but the component is stripping them out.

Eg, passing `TEST  [insert n number of spaces here]              TEST` will show the value `TEST TEST` and pass the incorrect value back through any callbacks/events.  

I haven't checked other components for the same issue.

![2020-04-17_10-51-12](https://user-images.githubusercontent.com/1646840/79598922-8e103580-8099-11ea-8afa-ba6cd97e3810.jpeg)

**Comment by craigkovatch** [comment]
This is the standard behavior of HTML. Please use `&nbsp;` or css `white-space` properties to adjust.

**Comment by tagyoureit** [comment]
Thanks for the help, @craigkovatch.  Per our other conversation, `&nbsp;` didn't work but `\xA0` did.

eg:
```
option.replace(/[ ]{2,}/mg, match => match.replace(/ /g, '\xA0'))
```
