### ISSUE TITLE
the link to Forums is broken

### ISSUE THREAD

**Issue by fosstin** [tableau/tableau-ui#31]
The "Forum" link in the header of https://tableau.github.io/tableau-ui is not working.  When I click it, sometimes I'm taken to a login page, but, whether or not I login, I see an error page.  If I try to put https://community.tableau.com/community/developers/ directly in the browser, I see this same error message.
![Screen Shot 2020-07-29 at 2 13 13 PM](https://user-images.githubusercontent.com/22079075/88837162-dca79280-d1a5-11ea-8392-abd234b75e5f.png)

**Comment by craigkovatch** [comment]
@benlower seems like something you would know about?

**Comment by KeshiaRose** [comment]
Updated, new page is here: https://community.tableau.com/s/developers
